try {
	throw 1234;
} catch (e) {
	console.log(e);
}